apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
  labels:
    app: oauth2-server
spec:
  replicas: {{ .Values.oauth2Server.replicaCount }}
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
        - name: oauth2-server
          image: "{{ .Values.oauth2Server.image.repository }}:{{ .Values.oauth2Server.image.tag }}"
          imagePullPolicy: {{ .Values.oauth2Server.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.oauth2Server.service.containerPort }}
          env:
            {{- range $key, $value := .Values.oauth2Server.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
