apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-server
  labels:
    app: resource-server
spec:
  replicas: {{ .Values.resourceServer.replicaCount }}
  selector:
    matchLabels:
      app: resource-server
  template:
    metadata:
      labels:
        app: resource-server
    spec:
      containers:
        - name: resource-server
          image: "{{ .Values.resourceServer.image.repository }}:{{ .Values.resourceServer.image.tag }}"
          imagePullPolicy: {{ .Values.resourceServer.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.resourceServer.service.containerPort }}
          env:
            {{- range $key, $value := .Values.resourceServer.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
