apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.oauthServer.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth-server-service
                port:
                  number: 9999