apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth-cache-comparison-oauth-client-ingress
  labels:
    app: oauth-client
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: oauth-client.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth-cache-comparison-oauth-client-service
                port:
                  number: 80