{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-acl
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  acl.conf: {{ .Values.aclConfig | b64enc | quote }}
{{- end }}
