spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server/issuer
          jwk-set-uri: http://auth-server/.well-known/jwks.json
          audiences:
            - your-audience-value