apiVersion: v1
kind: Service
metadata:
  name: oauth-server-service
  labels:
    app: oauth-server
spec:
  type: NodePort
  ports:
    - port: 9999
      targetPort: 8080
      protocol: TCP
      name: oauth-server-service
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: debug
      nodePort: 30500
  selector:
    app: oauth-server