apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oauth-client-service
  labels:
    app: oauth-client
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: oauth-client