apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
  labels:
    app: oauth2-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: oauth2-server