apiVersion: v1
kind: Service
metadata:
  name: oauth-server-service
  labels:
    app: oauth-server
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 8080
      protocol: TCP
      name: oauth-server-service
  selector:
    app: oauth-server