apiVersion: v1
kind: Service
metadata:
  name: resource-server-service
  labels:
    app: resource-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: resource-server-service
      port: {{ .Values.resourceServer.service.hostPort }}
      targetPort: {{ .Values.resourceServer.service.containerPort }}
      protocol: TCP
  selector:
    app: resource-server
