redisAclSecretName: redis-acl
redis-cluster:
  enabled: true
  usePassword: true
  password: "redis-password"  # Root password
  auth:
    enabled: true
    password: "redis-password"  # Same password in auth section
  cluster:
    nodes: 3
    replicas: 0
  configuration: |
    cluster-require-full-coverage no
    user jason_test on >testy ~* &* +@all
  persistence:
    enabled: false
  commonEnvironmentCfg:
    - name: REDIS_PASSWORD
      value: "redis-password"
    - name: REDIS_MASTER_PASSWORD
      value: "redis-password"
hazelcast:
  enabled: true
  mancenter:
    enabled: false
    initContainers:
      - name: clear-mc-lock
        image: busybox
        command: [ "sh", "-c", "rm -f /data/mc.lock || true" ]
        volumeMounts:
          - name: mancenter-data
            mountPath: /data
  cluster:
    memberCount: 2
memcached:
  enabled: true

oauthServer:
  replicaCount: 1
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-server
    tag: "1.0"
    pullPolicy: Always
  app:
    name: oauth2-server
  ingress:
    host: oauth2-server.local
  service:
    type: ClusterIP
    containerPort: 8080
    hostPort: 9999
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: "11211"
    HAZELCAST_HOST: hazelcast
    HAZELCAST_PORT: "5701"
    JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000


resourceServer:
  replicaCount: 1
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-resource
    tag: "1.0"
    pullPolicy: Always
  service:
    type: ClusterIP
    hostPort: 8081
    containerPort: 8080
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: "11211"
    HAZELCAST_HOST: hazelcast
    HAZELCAST_PORT: "5701"
    JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000

client:
  enabled: true
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-client
    tag: "1.0"
    pullPolicy: Always
