redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: default_password
  master:
    configuration: |
      aclfile /opt/bitnami/redis/conf/acl.conf
    persistence:
      enabled: false
    extraVolumes:
      - name: redis-acl
        secret:
          secretName: redis-acl
    extraVolumeMounts:
      - name: redis-acl
        mountPath: /opt/bitnami/redis/conf/acl.conf
        subPath: acl.conf
        readOnly: true
aclConfig: |
  user default on >default_password ~* &* +@all
  user jason_test on >testy ~* &* +@all

hazelcast:
  enabled: true
  mancenter:
    enabled: false
    initContainers:
      - name: clear-mc-lock
        image: busybox
        command: [ "sh", "-c", "rm -f /data/mc.lock || true" ]
        volumeMounts:
          - name: mancenter-data
            mountPath: /data
  cluster:
    memberCount: 2
memcached:
  enabled: true

oauthServer:
  replicaCount: 2
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-server
    tag: "1.0"
    pullPolicy: Always
  app:
    name: oauth2-server
  ingress:
    host: oauth2-server.local
  service:
    type: ClusterIP
    containerPort: 8080
    hostPort: 9999
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: "11211"
    HAZELCAST_HOST: hazelcast
    HAZELCAST_PORT: "5701"
  #  JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000


resourceServer:
  replicaCount: 1
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-resource
    tag: "1.0"
    pullPolicy: Always
  service:
    type: ClusterIP
    hostPort: 8081
    containerPort: 8080
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: "11211"
    HAZELCAST_HOST: hazelcast
    HAZELCAST_PORT: "5701"

client:
  enabled: true
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-client
    tag: "1.0"
    pullPolicy: Always
