caches:
  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: true
      password: foobar
      existingSecret: ""
      users:
        jason_test:
          password: testy
          commands:
            - allkeys
            - on
            - +@all
    master:
      persistence:
        enabled: false
  hazelcast:
    enabled: true
    cluster:
      memberCount: 2
  memcached:
    enabled: true

oauth2Server:
  replicaCount: 1
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-server
    tag: "1.0"
    pullPolicy: Always
  app:
    name: oauth2-server
  ingress:
    host: oauth2-server.local
  service:
    type: ClusterIP
    port: 8080
    hostPort: 9999
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: "11211"
    HAZELCAST_HOST: hazelcast
    HAZELCAST_PORT: "5701"


resourceServer:
  replicaCount: 2
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-resource
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: "11211"
    HAZELCAST_HOST: hazelcast
    HAZELCAST_PORT: "5701"

clientPod:
  enabled: true
  image:
    repository: jasonbuchanan145/oauth-cache-comparison-client
    tag: "1.0"
    pullPolicy: IfNotPresent
