caches:
  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
  hazelcast:
    enabled: true
    cluster:
      memberCount: 2
  memcached:
    enabled: true

oauth2Server:
  replicaCount: 1
  image:
    repository: your-docker-registry/oauth2-server
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: "11211"
    HAZELCAST_HOST: hazelcast
    HAZELCAST_PORT: "5701"


resourceServer:
  replicaCount: 2
  image:
    repository: your-docker-registry/resource-server
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: "11211"
    HAZELCAST_HOST: hazelcast
    HAZELCAST_PORT: "5701"

clientPod:
  enabled: true
  image:
    repository: your-docker-registry/client-pod
    tag: "1.0"
    pullPolicy: IfNotPresent
